# Generated by Django 5.1 on 2024-10-19 20:14

import django.db.models.deletion
import ecom_core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='minimum_order_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, validators=[ecom_core.validators.validate_bank_card_number])),
                ('iban', models.CharField(max_length=28, validators=[ecom_core.validators.validate_iban])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SellerBankAccount',
        ),
    ]
