# Generated by Django 5.1 on 2025-02-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_user_profile', '0002_sellerprofile_minimum_order_amount_bankcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='profile_picture',
        ),
    ]
