# Generated by Django 5.1 on 2025-03-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_user_profile', '0003_remove_customerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
