# Generated by Django 5.1 on 2025-03-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_user_profile', '0004_sellerprofile_store_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='rating',
        ),
    ]
