# Generated by Django 5.1 on 2025-04-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_user_profile', '0005_remove_sellerprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
