# Generated by Django 5.1 on 2025-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_user_profile', '0006_alter_sellerprofile_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
