# Generated by Django 5.0.6 on 2024-07-18 16:58

import django.utils.timezone
import ecom_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcomAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('OM', 'Order Manager'), ('IM', 'Inventory Manager'), ('SV', 'Super visor'), ('MG', 'Manager'), ('SA', 'Super admin')], max_length=2)),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(error_messages={'blank': 'The username cannot be blank', 'invalid': 'The username is invalid. Please refer to username definition constraints.', 'null': 'The username cannot be null', 'unique': 'The username already exists'}, help_text='Maximum of 100 characters. Only letters, digits and the special character . are allowed', max_length=100, unique=True, validators=[ecom_core.validators.validate_username], verbose_name='Username')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='AdminAccount Creation Date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
