services:
  next:
    build:
      context: ./frontend-new
      target: dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: next_app
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./frontend-new/pigikala/package.json
    volumes:
      - ./frontend-new/pigikala/src:/app/src
      - ./frontend-new/pigikala/public:/app/public
      - ./frontend-new/pigikala/package.json:/app/package.json
      - ./frontend-new/pigikala/next.config.ts:/app/next.config.ts
      - ./frontend-new/pigikala/tailwind.config.json:/app/tailwind.config.json
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CODE_REQUEST_COOLDOWN=${CODE_REQUEST_COOLDOWN_TIME}
      - CODE_LIFETIME=${CODE_LIFETIME}
      - API_BASE_URL=http://django:8000/
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME}
      - REFRESH_TOKEN_LIFETIME=${REFRESH_TOKEN_LIFETIME}
    env_file: .env
    depends_on:
      - django
