services:
  next:
    build:
      context: ./frontend-new
      target: dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: next_app
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./frontend-new/pigikala/package.json
        - action: sync
          path: ./frontend-new/pigikala/src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./frontend-new/pigikala/tailwind.config.json
          target: /app/tailwind.config.json
    environment:
      - CODE_REQUEST_COOLDOWN=${CODE_REQUEST_COOLDOWN_TIME}
      - CODE_LIFETIME=${CODE_LIFETIME}
      - API_BASE_URL=http://django:8000/
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME}
      - REFRESH_TOKEN_LIFETIME=${REFRESH_TOKEN_LIFETIME}
    env_file: .env
    depends_on:
      - django
