[tool.poetry]
name = "e-commerce backend"
version = "0.1.0"
description = ""
authors = ["Shervin Saeedi Borna <Shervinsaeedi78@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "4.2"
djangorestframework = "^3.14.0"
phonenumbers = "^8.13.29"
djangorestframework-simplejwt = "^5.3.1"
python-dotenv = "^1.0.1"
requests = "^2.31.0"
pytest-django = "^4.8.0"
pytest-cov = "^4.1.0"
redis = "^5.0.2"
django-extensions = "^3.2.3"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "ecom_core.settings"
python_files = "tests.py test_*.py *_tests.py"
addopts = "--cov-config=.coveragerc --cov=."

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"