[tool.poetry]
name = "e-commerce backend"
version = "0.1.0"
description = ""
authors = ["Shervin Saeedi Borna <Shervinsaeedi78@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "4.2"
djangorestframework = "^3.14.0"
phonenumbers = "^8.13.29"
djangorestframework-simplejwt = "^5.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
