# Generated by Django 5.0.6 on 2024-08-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_main_variant_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='productvariant',
            order_with_respect_to='product',
        ),
    ]
