# Generated by Django 5.1 on 2024-10-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productvariant_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
