# Generated by Django 5.1 on 2025-03-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_subcategory_subcategorybreadcrumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
