# Generated by Django 5.1 on 2025-03-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productvariant_color'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_color',
        ),
    ]
