# Generated by Django 5.1 on 2025-04-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_productvariant_unique_product_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategoryBreadCrumb',
            new_name='SubCategory',
        ),
    ]
