# Generated by Django 5.1 on 2025-04-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_subcategorybreadcrumb_subcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='technicaldetail',
            unique_together=set(),
        ),
    ]
