# Generated by Django 5.1 on 2025-04-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0012_rename_subcategorybreadcrumb_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.productvariant'),
        ),
    ]
