# Generated by Django 5.1 on 2025-03-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_productcomment_created_on_productcomment_updated_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productcomment',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
