# Generated by Django 5.1 on 2025-03-29 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_productreview_order_sellerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerreview',
            name='rating',
            field=models.IntegerField(default=5, help_text='Rating should be an integer from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
