# Generated by Django 5.1 on 2025-04-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_sellerreview_rating'),
        ('order', '0002_alter_orderitem_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
    ]
