# Generated by Django 5.0.6 on 2024-07-18 16:59

import django.db.models.deletion
import django.utils.timezone
import ecom_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_user.state')),
            ],
        ),
        migrations.CreateModel(
            name='EcomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, error_messages={'blank': 'The username cannot be blank', 'invalid': 'The username is invalid. Please refer to username help text.', 'null': 'The username cannot be null', 'unique': 'The username already exists'}, help_text='Maximum of 40 characters. Only letters, digits and the special character . are allowed', max_length=40, null=True, unique=True, validators=[ecom_core.validators.validate_username], verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[ecom_core.validators.validate_phone], verbose_name='Phone Number')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[ecom_core.validators.validate_national_code], verbose_name='National Code')),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='UserAccount Creation Date')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom_user.city')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom_user.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
