# Generated by Django 5.1 on 2025-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/customers/'),
        ),
    ]
