# Generated by Django 5.1 on 2025-01-25 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecom_admin', '0001_initial'),
        ('ecom_user_profile', '0002_sellerprofile_minimum_order_amount_bankcard_and_more'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=100)),
                ('api_endpoint', models.URLField()),
                ('status_check_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('is_verified', models.BooleanField(default=False, help_text='Indicating whether the money transfer request is valid or not.')),
                ('is_paid', models.BooleanField(default=False)),
                ('tracking_code', models.IntegerField(blank=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requesting user')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom_admin.ecomadmin', verbose_name='Verified by admin')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipg_service', models.IntegerField(blank=True)),
                ('is_used', models.BooleanField(default=False, help_text='This field indicates that whether this payment has been checked to either update an order to PAID status, or to increase the balance of a wallet.')),
                ('track_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('CC', 'Cancelled'), ('UP', 'Unpaid'), ('PY', 'Paying'), ('PD', 'Paid')], max_length=2)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='order.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text="If the transaction's type is order revenue", max_digits=5, null=True)),
                ('type', models.CharField(choices=[('PM', 'Deposit'), ('WD', 'Withdrawal'), ('OR', 'Order Revenue'), ('OP', 'Order Direct Payment'), ('WP', 'Order Wallet Payment'), ('CC', 'Cancellation')], max_length=2)),
                ('order', models.ForeignKey(blank=True, help_text='If an order is involved in the transaction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
                ('payment', models.ForeignKey(blank=True, help_text="If the transaction's type has a payment involved", null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeops.payment')),
                ('wallet', models.ForeignKey(blank=True, help_text='If the wallet is involved in the transaction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='financeops.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='financeops.wallet'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AP', 'PAID'), ('RF', 'Refused'), ('PD', 'Pending')], default='PD', max_length=2)),
                ('amount', models.PositiveBigIntegerField()),
                ('refuse_reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='ecom_user_profile.bankcard')),
            ],
        ),
    ]
