# Generated by Django 5.1 on 2024-10-20 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecom_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=100)),
                ('api_endpoint', models.URLField()),
                ('status_check_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipg_service', models.IntegerField(blank=True, choices=[(1, 'Zibal'), (2, 'Asan Pardakht')])),
                ('is_used', models.BooleanField(default=False, help_text='This field indicates that whether this payment has been checked to either update an order to PAID status, or to increase the balance of a wallet.')),
                ('track_id', models.CharField(max_length=50)),
                ('track_id_time', models.DateTimeField(help_text='When `track_id` field is provided/updated, this field should be set to its time')),
                ('status', models.CharField(choices=[('CC', 'Cancelled'), ('UP', 'Unpaid'), ('PY', 'Paying'), ('PD', 'Paid')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text="If the transaction's type is order revenue", max_digits=5, null=True)),
                ('type', models.CharField(choices=[('PM', 'Deposit'), ('WD', 'Withdrawal'), ('OR', 'Order Revenue'), ('OP', 'Order Direct Payment'), ('WP', 'Order Wallet Payment'), ('CC', 'Cancellation')])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AP', 'PAID'), ('RF', 'Refused'), ('PD', 'Pending')], default='PD', max_length=2)),
                ('amount', models.PositiveBigIntegerField()),
                ('refuse_reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('is_verified', models.BooleanField(default=False, help_text='Indicating whether the money transfer request is valid or not.')),
                ('is_paid', models.BooleanField(default=False)),
                ('tracking_code', models.IntegerField(blank=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requesting user')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom_admin.ecomadmin', verbose_name='Verified by admin')),
            ],
        ),
    ]
