# Generated by Django 5.1 on 2025-04-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='paid_by',
        ),
    ]
