# Generated by Django 5.1 on 2025-04-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeops', '0002_rename_user_payment_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ipg_service',
            field=models.IntegerField(choices=[('ZB', 'Zibal'), ('AP', 'Asan Pardakht')], max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='track_id',
            field=models.CharField(help_text="Payment's track id which is provided by the IPG service", max_length=50, unique=True),
        ),
    ]
