# Generated by Django 5.1 on 2025-01-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeops', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='track_id_time',
        ),
        migrations.AlterField(
            model_name='payment',
            name='ipg_service',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='track_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PM', 'Deposit'), ('WD', 'Withdrawal'), ('OR', 'Order Revenue'), ('OP', 'Order Direct Payment'), ('WP', 'Order Wallet Payment'), ('CC', 'Cancellation')], max_length=2),
        ),
    ]
