# Generated by Django 5.1 on 2025-04-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeops', '0003_alter_payment_ipg_service_alter_payment_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ipg_service',
            field=models.CharField(choices=[('ZB', 'Zibal'), ('AP', 'Asan Pardakht')], max_length=2),
        ),
    ]
